課題１エラー
API Testerの結果
status: 400,
error: "Bad Request",
message: "Required request body is missing: public com.example.entity.Account com.example.controller.AccountController.open(com.example.resource.RequestAmount)",
path: "/bankTrading/open"